fprintf('Executing step 1 of computational framework... \n');

if(params_step1.is_diffuser==1)
    % activate non-trivial convolution kernel
    kernel = fspecial('gaussian',20,0.8); %a 20X20 kernal, sigma=0.8=0.8*180/3.14=45 degree
    A = @(x) conv2(x,kernel,'same');
    AT = @(x) conv2(x,kernel,'same');
elseif(params_step1.is_diffuser==0)
    A = @(x) x;
    AT = @(x) x;
end

% run optimization solver for fluorescence intensity
C_hat = SPIRALTAP(C_raw,A,params_step1.tau,...
    'penalty','TV',...
    'AT',AT,...
    'Initialization',C_raw,...
    'miniter',params_step1.miniter,...
    'maxiter',params_step1.maxiter,...
    'stopcriterion',params_step1.stopcriterion,...
    'tolerance',params_step1.tolerance,...
    'monotone',1,...
    'saveobjective',1,...
    'savereconerror',1,...
    'savecputime',1,...
    'savesolutionpath',0,...
    'truth',C_raw,...
    'verbose',0);