fprintf('Executing step 4 of computational framework... \n');

finit = 1./Y;
finit(~M) = 0;
finit(isinf(finit)) = 0;
finit(masks)= 0;

A_lifetime = @(x) x;
AT_lifetime = @(x) x;

% run optimization solver for fluorescence lifetime
INVLT_hat = SPIRALTAP_FLIM(Y,A_lifetime,params_step3.tau,...
    'noisetype','exponential',...
    'penalty','tv',...
    'AT',AT_lifetime,...
    'Initialization',finit,...
    'miniter',params_step3.miniter,...
    'maxiter',params_step3.maxiter,...
    'stopcriterion',params_step3.stopcriterion,...
    'tolerance',params_step3.tolerance,...
    'monotone',1,...
    'saveobjective',1,...
    'savereconerror',1,...
    'savecputime',1,...
    'savesolutionpath',0,...
    'truth',Y,...
    'verbose',0);
LT_hat = 1./INVLT_hat;
LT_hat_filt_temp = LT_hat;
LT_hat_filt_temp(~M) = nan;
% optional bg filtering
C_sc = C_hat_filt;
A_sc = max(C_sc-params_step3.B_sc*params_step3.t_r,eps);
LT_hat_filt = max((LT_hat_filt_temp.*C_sc-params_step3.B_sc*(0.5*params_step3.t_r^2))./A_sc,eps);
